# File: datasets/config.yaml

kitti:
  root: "."                # as before
  splits:
    train:
      images: "data_object_image_2/training"
      lidar:  "data_object_velodyne/training"
    test:
      images: "data_object_image_2/testing"
      lidar:  "data_object_velodyne/testing"

nuscenes:
  root: "v1.0-mini"

# the “vanilla” full set (no filtering)
nuscenes-full:
  root: "v1.0-full"

# now our *named* subsets:
nuscenes-full-night:
  root: "v1.0-full"
  visibility_filters: [night]

nuscenes-full-rain:
  root: "v1.0-full"
  visibility_filters: [rain]


# combined adverse weather:
nuscenes-full-adverse:
  root: "v1.0-full"
  visibility_filters:
    - night
    - rain
